set(THREEPHASESEPLUGIN_NAME tpseconvmp)

file(GLOB THREEPHASESEPLUGIN_CPP_COMMON_SOURCES ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB THREEPHASESEPLUGIN_CPP_COMMON_INCS ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_GUI ${NATID_SDK_INC}/gui/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_TD ${NATID_SDK_INC}/td/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_CNT ${NATID_SDK_INC}/cnt/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_MU ${NATID_SDK_INC}/mu/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_MEM ${NATID_SDK_INC}/mem/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_FO ${NATID_SDK_INC}/fo/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_SC ${NATID_SDK_INC}/sc/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_SYST ${NATID_SDK_INC}/syst/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_DENSE ${NATID_SDK_INC}/dense/*.h)
file(GLOB THREEPHASESEPLUGIN_INC_SPARSE ${NATID_SDK_INC}/sparse/*.h)

add_library(${THREEPHASESEPLUGIN_NAME} SHARED
	${THREEPHASESEPLUGIN_CPP_COMMON_SOURCES}
	${THREEPHASESEPLUGIN_CPP_COMMON_INCS}
	${THREEPHASESEPLUGIN_INC_GUI}
	${THREEPHASESEPLUGIN_INC_TD}
	${THREEPHASESEPLUGIN_INC_SYST}
	${THREEPHASESEPLUGIN_INC_CNT}
	${THREEPHASESEPLUGIN_INC_MU}
	${THREEPHASESEPLUGIN_INC_MEM}
	${THREEPHASESEPLUGIN_INC_FO}
	${THREEPHASESEPLUGIN_INC_SC}
	${THREEPHASESEPLUGIN_INC_DENSE}
	${THREEPHASESEPLUGIN_INC_SPARSE})

source_group("inc\\inc" FILES ${THREEPHASESEPLUGIN_CPP_COMMON_INCS})
source_group("inc\\gui" FILES ${THREEPHASESEPLUGIN_INC_GUI})
source_group("inc\\td" FILES ${THREEPHASESEPLUGIN_INC_TD})
source_group("inc\\cnt" FILES ${THREEPHASESEPLUGIN_INC_CNT})
source_group("inc\\dense" FILES ${THREEPHASESEPLUGIN_INC_DENSE})
source_group("inc\\mu" FILES ${THREEPHASESEPLUGIN_INC_MU})
source_group("inc\\mem" FILES ${THREEPHASESEPLUGIN_INC_MEM})
source_group("inc\\fo" FILES ${THREEPHASESEPLUGIN_INC_FO})
source_group("inc\\sc" FILES ${THREEPHASESEPLUGIN_INC_SC})
source_group("inc\\sparse" FILES ${THREEPHASESEPLUGIN_INC_SPARSE})
source_group("inc\\syst" FILES ${THREEPHASESEPLUGIN_INC_SYST})
source_group("src\\cpp" FILES ${THREEPHASESEPLUGIN_CPP_COMMON_SOURCES})

target_link_libraries(${THREEPHASESEPLUGIN_NAME}
	debug ${MU_LIB_DEBUG} optimized ${MU_LIB_RELEASE}
	debug ${MATRIX_LIB_DEBUG} optimized ${MATRIX_LIB_RELEASE}
	debug ${NATGUI_LIB_DEBUG} optimized ${NATGUI_LIB_RELEASE})

target_compile_definitions(${THREEPHASESEPLUGIN_NAME} PUBLIC PLUGIN_EXPORTS)

setIDEPropertiesForLib(${THREEPHASESEPLUGIN_NAME})

add_custom_command(TARGET ${THREEPHASESEPLUGIN_NAME} POST_BUILD
	COMMAND ${CMAKE_COMMAND} -E echo "Built plugin DLL: $<TARGET_FILE:${THREEPHASESEPLUGIN_NAME}>"
	COMMAND ${CMAKE_COMMAND} -E echo "For dTwin release app, copy the Release x64 tpseconvmp.dll manually to dTwin/res/plugins."
	VERBATIM)

set(DTWIN_EXE "" CACHE FILEPATH "Optional path to dTwin.exe used only for Visual Studio debugging. DLL is not copied automatically.")
if (DTWIN_EXE AND EXISTS "${DTWIN_EXE}")
	get_filename_component(DTWIN_EXE_DIR "${DTWIN_EXE}" DIRECTORY)
	add_custom_target(run_dTwin
		COMMAND "${DTWIN_EXE}"
		WORKING_DIRECTORY "${DTWIN_EXE_DIR}"
		COMMENT "Starting dTwin.exe")
	set_property(DIRECTORY PROPERTY VS_STARTUP_PROJECT run_dTwin)
endif()
